# Generated by Django 3.0.6 on 2020-06-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200617_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='new',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
