# Generated by Django 3.0.6 on 2020-06-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20200618_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
