# Generated by Django 3.0.6 on 2020-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20200618_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
