# Generated by Django 3.0.6 on 2020-06-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_email_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='status',
        ),
    ]
